# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f750426811b961e667c046f322efd0f819596a23493fbb7bebc2e556cbeaee6fa83e14aed6e3a29dccdff35dcab8909582917e0ab5d961532a1f599021a46c

test:
  secret_key_base: 5410b4341534d7e8a3a5151d6c4cab69e2a37d46219cbe45b47adfc8ba2ec633f766e2ede071c8d200769153f28dbd8eae19be160fce5a57d90a0cbbdd1e238e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
